### ISSUE TITLE
Cannot use array parameter in SqlBuilder

### ISSUE THREAD

**Issue by maxtoroq** [maxtoroq/DbExtensions#10]
**NOTE: In v6, this is no longer an issue. For more information see [SqlBuilder Tutorial: Lists](http://maxtoroq.github.io/DbExtensions/docs/SqlBuilder.html#lists).**

e.g.

``` csharp
byte[] data = GetImageData();

db.Affect(SQL
   .UPDATE("images")
   .SET("image = {0}", data)
   ...
```

Need to workaround [parameter expansion](https://github.com/maxtoroq/DbExtensions/blob/v5/docs/SqlBuilder.md#arrays), like this:

``` csharp
db.Affect(SQL
   .UPDATE("images")
   .SET("image = {0}", new object[] { new object[] { data } })
   ...
```

**Comment by maxtoroq** [comment]
In v6, this is no longer an issue. For more information see [SqlBuilder Tutorial: Lists](http://maxtoroq/github.io/DbExtensions/docs/SqlBuilder.html#lists).

**Comment by Gillardo** [comment]
Cannot find SQL.param in latest code ??  Has it been removed?  I am having trouble adding the byte[] array

> ArgumentException: No mapping exists from object type System.Int64[] to a known managed provider native type.

**Comment by maxtoroq** [comment]
`SQL.Param` was dropped in v6. Arrays are no longer special. To expand an array into a list you must call `SQL.List`.

**Comment by Gillardo** [comment]
And this also applies to byte[] when the field is a concurrency field?

**Comment by maxtoroq** [comment]
No, it shouldn't. Perhaps if you show me some code I can help.

**Comment by Gillardo** [comment]
Same code as at the top of here #39

**Comment by maxtoroq** [comment]
Looks like a provider issue. If `System.Int64[]` is the type of the parameter, looks like the provider is getting the same type but for some reason not liking it.
