### ISSUE TITLE
Make SqlBuilder.cs a standalone file

### ISSUE THREAD

**Issue by iyilm4z** [maxtoroq/DbExtensions#30]
Dear Max Toro,
I use Dapper as my Micro ORM Tool as you already familiar with it. After a while it made me bored to build raw sql queries also i wanted to do something better with building Sql queries and thats why i looked for a Sql Builder Framework and i found your implementation as best Sql Builder. My problem is i just want to use your SqlBuilder.cs file by importing it to my project as file not using nuget package, because i want to see whats going on behind the scenes by debugging. I copied and pasted your SqlBuilder.cs class to my project and i realized that it has dependencies on another class which you named DbExtentions.cs. SqlBuilder.cs class needs Mapper class in DbExtentions.cs like below code line 
<code>
 internal static IEnumerable<TResult> Map<TResult>(Func<SqlBuilder, IDbCommand> queryToCommand, SqlBuilder query, Mapper mapper, TextWriter logger) 
</code>
I actually want you to make SqlBuilder.cs class has no dependecies and can be useable like Dapper as single file. Also i dont wanna import classes that i dont need to use like other classes(wish i could but its a bit late) Its actually possible to copy and paste the scripts from DbExtentions.cs class to SqlBuilder.cs class but i thought maybe you have better solution because you are the professionel and i'm just a copy-paste master:)

Thanks for sharing your this perfect codes with us..

**Comment by ismailyilmaz** [comment]
Dear Sir,
Thanks for fast reply, I am really appreciated, now it's just an awesome framework, keep making us happier..:)
