### ISSUE TITLE
SqlServer 2008 support in SqlSet

### ISSUE THREAD

**Issue by cnsharp** [maxtoroq/DbExtensions#33]
I found that SqlSet.Take and Skip method are based on SQL 2012.How can I do that in SQL 2008?
Thanks!

**Comment by maxtoroq** [comment]
I'll see what I can do. Looks similar to Oracle's paging, using `ROW_NUMBER() OVER(ORDER BY )`.

**Comment by maxtoroq** [comment]
@cnsharp SqlServer 2008 support is complete. Please checkout the master branch to try it out. You have to decorate your database class with `[Provider(typeof(Sql2008Provider))]` to enable it, e.g.:

```csharp
[Provider(typeof(Sql2008Provider))]
class Sql2008Database : Database {
   ...
}
```

**Comment by cnsharp** [comment]
Thank you very much!You are so quickly and dedicated.I'll try it now.

**Comment by cnsharp** [comment]
@maxtorop
Hi Max,

Our DBA recommended a style like this which has a better performance in the middle of many pages

WITH
ID AS(
    SELECT
        __row_id = ROW_NUMBER() OVER(order by id DESC),
        id
    FROM dbo.tb WITH(NOLOCK)
    WHERE column_id = 1
)
SELECT
    ID.__row_id,
    DATA.*
FROM ID
    INNER JOIN dbo.tb DATA WITH(NOLOCK)
        ON DATA.id = ID.id
WHERE ID.__row_id BETWEEN 5000 AND 5100
;

I want to implement it by myself.
The question is how can I  pass id/primary key to SqlSet?Maybe I could add an id property to SqlSet.

What is your opinion?
Thanks!

**Comment by maxtoroq** [comment]
@cnsharp That level of fine tuning is not supported, use SqlBuilder instead. If you have more questions please create a new issue.
