### ISSUE TITLE
Parameter with byte[] not adding correctly

### ISSUE THREAD

**Issue by Gillardo** [maxtoroq/DbExtensions#39]
On my entity i have a rowVersion field which in SQL is stored as timestamp.  I convert this in SQL to byte[].

When i want to update my entity i have building sql like so

    var updateBuilder = SQL
        .FROM("myTable")
        .SET("UpdatedDate = {0}", updated.UpdatedDate)
        .SET("UpdatedByUserId = {0}", updated.UpdatedByUserId)
        .WHERE("Id = {0}", updated.Id)
        .WHERE("RowVersion = {0}", updated.RowVersion);

But it is creating multiple paremeters for my rowVersion (a string for each element in the array).  here is the SQL it is creating

    exec sp_executesql N'UPDATE myTable
    SET UpdatedDate = @p0, UpdatedByUserId = @p1
    WHERE Id = @p2 AND RowVersion = @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10

In entity framework, when a byte array is added it adds a parameter like so

    @3=0x0000000000560F94

Am i doing something wrong?

**Comment by maxtoroq** [comment]
See #10

**Comment by Gillardo** [comment]
Thank u. Think it maybe helpful if this was on the readme or tutorial pages.

Thanks again
