### ISSUE TITLE
Need to "extend" clause

### ISSUE THREAD

**Issue by Gillardo** [maxtoroq/DbExtensions#41]
I think the _OR clause is great, but i need to extend the OR group with additional checks.

Could we have an "ExtendClause" method which basically, removes the last bracket, inserts the additional clause and adds the bracket onto the end?

Something like this.  Would this work, can you see any problems with it?

    public SqlBuilder ExtendClause(format, parameters) 
    {
        // remove last )
        sqlBuilder.Buffer.Length -= 1;
        // insert additional clause
        sqlBuilder.Append(format, parameters);
        // re-add bracket
        sqlBuilder.Append(")");
    }

This could be then used like this

    var builder = SQL
        .SELECT("*")
        .FROM("myTable")
        .WHERE("(Field1 = {0} OR Field2 = {1})", new object[] { "Test", "Test" })
        .ExtendClause("OR Field1 IS NULL", null);

This should then produce SQL 

    SELECT * FROM myTable
    WHERE (Field1 = @p1 OR Field2 = @p2 OR Field1 IS NULL)

This method is handly for when you use the _OR method really as it adds brackets around the OR clause

**Comment by maxtoroq** [comment]
No need to be out of the box, make it an extension method.
