### ISSUE TITLE
dotnet core version

### ISSUE THREAD

**Issue by Gillardo** [maxtoroq/DbExtensions#44]
Is there going to be a version of this created that will support dotnet core?

**Comment by maxtoroq** [comment]
Not using .net core anytime soon.

**Comment by Worldcycler** [comment]
.net core is now allready RC2 and supported by Microsoft on production environments.
It would be great if there could be a .Net Core version.

**Comment by maxtoroq** [comment]
@Worldcycler ask your employer to support open source.

**Comment by maxtoroq** [comment]
I plan on supporting .NET Core on v6, but only including SqlBuilder, SqlSet and Database. SqlTable depends on System.Data.Linq.Mapping, if anyone wants to fork it from referencesource and make it work on .NET Core then I'd be happy to use it.

**Comment by maxtoroq** [comment]
Planning on supporting .NET Core 2.0, waiting for RTM. Need testers though.

**Comment by Gillardo** [comment]
Happy to be involved, whether means testing or coding.

**Comment by maxtoroq** [comment]
@Gillardo Great. Stay tuned.

**Comment by maxtoroq** [comment]
.NET Standard 2.0 does not include `DbProviderFactories`, see dotnet/corefx#20903

Need to investigate what other ORMs are doing as a workaround, or keep waiting.

**Comment by maxtoroq** [comment]
Using convention-based `DbProviderFactories`. Will work for most providers.

@Gillardo The `dev-netstd` branch has a new project called `DbExtensions.netstd`. Give it a try and let me know how it goes.

**Comment by Gillardo** [comment]
Thanks @maxtoroq will look at using this shortly

**Comment by Gillardo** [comment]
@maxtoroq i am guessing there is no nuget package for this yet?  I have to build from source and reference in my project?

**Comment by maxtoroq** [comment]
@Gillardo Yep.

**Comment by TwitchBronBron** [comment]
@maxtoroq if I did the work to set up appveyor scripts, would you be open to publishing nightly prerelease dotnet core versions of this library to nuget or myget so we don't have to pull down and compile ourselves?

**Comment by maxtoroq** [comment]
@TwitchBronBron I'd be happy to pack a pre-release if someone does some testing to make sure it actually works.

**Comment by TwitchBronBron** [comment]
@maxtoroq I'd be more than willing to do some testing to verify it actually works. Let me know how I can help!

**Comment by maxtoroq** [comment]
@TwitchBronBron I just need someone to use it successfully in a real .NET Core project.

**Comment by damiensawyer** [comment]
If anyone is interested, I 'think' that I got it working ish in netstandard 2.0. I've not published a nuget, however the code is https://github.com/damiensawyer/dbextensionscore/commits/master
Basically I created a netstandard2.0 project, copied in the code, deleted anything that wouldn't compile, added it to our other project and all our tests passed. I have no idea what the code did that I deleted... but what remains "works for us with the basics".

**Comment by maxtoroq** [comment]
I've just published 6.2.0-preview1 which supports `netcore2.1`. Cannot do `netstandard2.0` until it includes `DbProviderFactories`. @Gillardo @TwitchBronBron @damiensawyer

**Comment by maxtoroq** [comment]
Leaning towards waiting for `netstandard2.1`

**Comment by TwitchBronBron** [comment]
@maxtoroq we've been using 6.2.0-preview1 at work for a few weeks now (in development), and it seems to be working great with the parts we use. Thanks for getting that put together .

**Comment by doriant** [comment]
Hello! Can anybody help me? I use the DbExtensions framework in my plugin for NopCommerce 4.10 which uses the .net core 2.1 platform. I installed the DbExtensions (v6.2.0-preview2) from the Package Manager console and added the appropriate namespace in my class. Visual Studio sees DbExtensions but when I try to call a class from it ('Database' for example), I get an exception:
'Could not load file or assembly 'DbExtensions, Version=6.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'
Maybe I missed something? Thanks.

**Comment by maxtoroq** [comment]
v6.2.0-preview3 now supports both .NET Core 2.1 and .NET Standard 2.1

**Comment by maxtoroq** [comment]
Shipped in v6.2.0
