### ISSUE TITLE
Support explicit DbParameter on CreateCommand

### ISSUE THREAD

**Issue by ensemblebd** [maxtoroq/DbExtensions#46]
Sorry to bother again, but am not able to create a query that inserts/updates spatial data.

http://stackoverflow.com/questions/5644466/updating-sql-server-2008-records-w-spatial-data-types-via-massive-orm-executen

The error is as seen in that thread. However there is no way to specify that property for the value, it would seem?

I'm simply trying to use `SqlGeometry myvalue = SqlGeometry.Point(this.Lat, this.Lon, WGS84_SRID);`
And when passed in VALUES() it fails. But I'm not seeing a way to pass in a SqlParameter manually to the collection?

**Comment by maxtoroq** [comment]
Currently, you cannot use an explicit DbParameter with SqlBuilder. The workaround is to use `null` instead, create the command and modify/replace the parameter.

I think it would be a good improvement to support explicit DbParameter for special cases like this. I'll work on it.

**Comment by ensemblebd** [comment]
Awesome thank you, I'll give this a try. Definitely appreciate the support and assistance.

**Comment by maxtoroq** [comment]
Included in v6
