### ISSUE TITLE
There is already an open DataReader associated with this Connection which must be closed first

### ISSUE THREAD

**Issue by vikasmohal** [maxtoroq/DbExtensions#63]
**Is there any way to create multiple Recordset for each Include....**

An unhandled exception of type 'MySql.Data.MySqlClient.MySqlException' occurred 

Additional information: There is already an open DataReader associated with this Connection which must be closed first.

**Comment by maxtoroq** [comment]
If the provider doesn't support MARS, you can only eager-load a one-to-many association for a single entity, e.g. using Single or First.
