### ISSUE TITLE
Association with multiple keys

### ISSUE THREAD

**Issue by jerauskin** [maxtoroq/DbExtensions#70]
Hello, I am usiing this awesome librery but I have a question. Is it possible to use association in SqlSet with multiple keys like this ?

```
        [Column(IsPrimaryKey = true, IsDbGenerated = false)]
        public string CodigoAlmacen { get; set; }
        [Column(IsPrimaryKey = true, IsDbGenerated = false)]
        public string CodigoArticulo { get; set; }
        [Column]
        public string Ubicacion { get; set; }
        [Column]
        public Nullable<double> StockMinimo { get; set; }
        [Column]
        public Nullable<double> StockMaximo { get; set; }
```
Thanks

**Comment by maxtoroq** [comment]
Yes, multi-column keys are supported, although some methods only work with single-column keys, like Find and ContainsKey.

**Comment by jerauskin** [comment]
Thanks, but I don't see in documentacion how I should implement that. I only see that:

```
        [Association(ThisKey = nameof(CodigoAlmacen)]
        public StockMinMax StockMinMax { get; set; }
```
There is only one "ThisKey" on each Association

Best regards

**Comment by maxtoroq** [comment]
For multi-column keys use a comma-separated list. e.g.:

```csharp
[Association(ThisKey = "CodigoAlmacen,CodigoArticulo")]
```

**Comment by jerauskin** [comment]
Ok, thanks
