### ISSUE TITLE
Use same parameter when value is the same

### ISSUE THREAD

**Issue by Gillardo** [maxtoroq/DbExtensions#78]
If i create a query and pass in the same parameter value, it generates a new parameter for this.  It would be much more efficient if the code only added 1 parameter for each unique value instead.

Can this be done?

**Comment by maxtoroq** [comment]
This could be done, but unless you are using a huge number of parameters, I don't see a big perf gain. It would also be a breaking change for code that depends on the number of parameters generated.

**Comment by Gillardo** [comment]
We are generating queries and putting them all together so it's only one database connection, I think this would be a good changed. At the moment it easily generates over 2000 parameters but it's around 4 values

**Comment by maxtoroq** [comment]
You can override the CreateCommand method on Database.

Another perf issue I can think of is parameter equality. Every time you add a parameter you have to check if it's equal to any of the previously added. That is unless you use something like a hash code.

**Comment by maxtoroq** [comment]
https://github.com/maxtoroq/DbExtensions/blob/b2c096576d1619ef724b9ac9df257ba8567de462/src/DbExtensions/Database.cs#L412

**Comment by maxtoroq** [comment]
Closing as this is a breaking change.
