### ISSUE TITLE
ColumnAttribute Name does not work

### ISSUE THREAD

**Issue by EthemAcar-Dev** [maxtoroq/DbExtensions#81]
public class MyTableName
{
[Column(Name = "nOffer")]
public int Offer { get; set; }
}

This is my entity model. When I Map my query using DBExtensions I get 100 results back but the values are all 0.

If i change the property to table name like:

[Column(Name = "nOffer")]
public int nOffer { get; set; }

Then i get correct values.

**Comment by maxtoroq** [comment]
How are you building the query? If you are using SqlBuilder or a plain string, you are responsible for the column to property mapping.

**Comment by EthemAcar-Dev** [comment]
var query = SQL.SELECT("TOP (1) *").FROM("MyTableName");
var execution = _db.Map<MyTableName>(query)?.First();

Isn't this the correct way?

**Comment by maxtoroq** [comment]
Try this:

```csharp
var execution = _db.Table<MyTableName>()
    .First();
```

**Comment by EthemAcar-Dev** [comment]
> Try this:
> 
> ```cs
> var execution = _db.Table<MyTableName>()
>     .First();
> ```

Gives the same result back as my previous code.
Seems like Column name property is not working correctly? Which is bad for me because there are some columns that start with numbers on my database and C# does not accept numbers as property names.

**Comment by maxtoroq** [comment]
Are you using the Table attribute on the entity class?

**Comment by EthemAcar-Dev** [comment]
> Are you using the Table attribute on the entity class?

 [Table(Name = "MyTableName")]
 public class MyTableName
 {
 [Column(Name = "nOffer")]
public int Offer { get; set; }
 }
 
 Yeah like this.

**Comment by maxtoroq** [comment]
I cannot reproduce the issue. If you call `_db.Table<MyTableName>().GetDefiningQuery().ToString()` what do you get? That way we can find out if it's using the column name or not.

**Comment by EthemAcar-Dev** [comment]
Aha my bad it all makes sense right now.

DbExtensions uses the given Column name value to build SQL like:

```c
SELECT [nOffer] AS [Offer]
FROM [MyTableName]
```
So if i build a query using DbExtensions SQL object i should type it as follow:
```c
SQL.Select("TOP [nOffer] AS [Offer]"); 
```
Which returns the correct database value.

Thank you very much for the support.
